In [15]:
import pandas as pd

df_events = pd.read_csv('events.csv')
df_events = df.dropna(axis=1,how='all')
df_events.columns = df_events.columns.str.lower()
df_events.shape



df_clt = pd.read_excel('cltdata.xlsx')
df_clt.columns = df_clt.columns.str.lower()
df_clt.head()

,name,id,quarter,complete__c,createddate,start_date__c,start_quarter__c,start_year__c,calling_quarter__c,question_2__c,...,clinicals_view_months_tenure,migration_tenure,migration_date,migration_month,last_completed_clt_quarter,last_completed_clt_nps_rank,last_completed_clt_nps_code,last_completed_clt_nps_response,completed_most_recent_clt,last_completed_clt_clinicals_view
0,SR-74047,a1FG0000005Z4D3MAK,2017 - Q1,1,2017-01-06 18:27:54,2017-01-09 00:00:00,1.0,2017.0,Q1/Q3,If in the past 12 months you’ve negotiated a c...,...,5.0,5.0,5.0,August,2016 - Q3,Promoter,100.0,10.0,1.0,NaN
1,SR-74048,a1FG0000005Z4D4MAK,2017 - Q1,1,2017-01-06 18:27:54,2017-01-09 00:00:00,1.0,2017.0,Q1/Q3,If in the past 12 months you’ve negotiated a c...,...,9.0,9.0,9.0,April,2016 - Q3,Promoter,100.0,9.0,1.0,Migration
2,SR-74049,a1FG0000005Z4D5MAK,2017 - Q1,1,2017-01-06 18:27:54,2017-01-09 00:00:00,1.0,2017.0,Q1/Q3,If in the past 12 months you’ve negotiated a c...,...,16.0,NaN,NaN,NaN,2016 - Q3,Promoter,100.0,9.0,1.0,Net New
3,SR-74050,a1FG0000005Z4D6MAK,2017 - Q1,0,2017-01-06 18:27:54,2017-01-09 00:00:00,1.0,2017.0,Q1/Q3,If in the past 12 months you’ve negotiated a c...,...,4.0,4.0,4.0,September,2016 - Q3,Passive,0.0,8.0,1.0,NaN
4,SR-74051,a1FG0000005Z4D7MAK,2017 - Q1,0,2017-01-06 18:27:54,2017-01-09 00:00:00,1.0,2017.0,Q1/Q3,If in the past 12 months you’ve negotiated a c...,...,6.0,6.0,6.0,July,2016 - Q3,Promoter,100.0,10.0,1.0,Migration

In [26]:
#df_clt_time = df_clt.loc[:,['id',pd.to_datetime('createddate',format='%Y-%m-%d %H:%M:%S').timestamp.dt.hour]]
#df_clt_time.head()
df_clt['createddate'].dtype

dtype('<M8[ns]')